### ISSUE TITLE
vue+supabase supabaseOptions is not being respected by nuxt+supabase

### ISSUE THREAD

**Issue by rotemrevivo91** [supabase-community/nuxt-supabase#16]
Example - passing a different schema:
```
  modules.push(['nuxt-supabase', {
    supabaseUrl,
    supabaseKey,
    supabaseOptions: {schema: "somethingelse"}
  }])
```
But the schema remains public and nothing changes.

### Expected behavior
```
VueSupabaseClient {
  ..
  schema: "somethingelse"
}

**Comment by rotemrevivo91** [comment]
```js

   
import Vue from "vue";
import { createVueSupabase } from "vue-supabase";
const supabase = createVueSupabase({
  supabaseUrl: "<%= options.supabaseUrl %>",
  supabaseKey: "<%= options.supabaseKey %>",
  # HERE IS WHAT NEED TO CHANGE
  supabaseOptions: "<%= options.supabaseOptions %>",
});

Vue.use(supabase);

// Inject Supabase into Nuxt Context
export default (ctx, inject) => {
  ctx.$supabase = supabase;
  inject("supabase", supabase);
};

**Comment by rotemrevivo91** [comment]
i created a pull request. Hope you can approve it soon if everything seems alright :)

**Comment by vejja** [comment]
Would love to see this merged also.
I tested PR [a36586b](https://github.com/supabase-community/nuxt-supabase/pull/17/commits/a36586b40908f0a0e5b92110d8b1954baa30be3c) on my end and it works fine.

**Comment by rotemrevivo91** [comment]
@vejja you're more than welcome to use my fork https://github.com/rotemrevivo91/nuxt-supabase seems like the guy started this doesn't care anymore

**Comment by scottrobertson** [comment]
> @vejja you're more than welcome to use my fork https://github.com/rotemrevivo91/nuxt-supabase seems like the guy started this doesn't care anymore

Or we are busy.
